### ISSUE TITLE
How to use with npm private registry

### ISSUE THREAD

**Issue by crtdaniele** [chris5287/dependabot-for-azuredevops#30]
Hi,
I will want to use this repo with a npm private registry on azure.

In my file run.rb I insert this config:

credentials = [
{
"type" => "npm_registry",
"token" => "",
"registry" => "", (the path of registry without https://
},
{
"type" => "git_source",
"host" => "dev.azure.com",
"username" => "x-access-token",
"password" => ""
}
]

In the pipeline on Azure: Failed processing: The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): path_of_registry

Any idea?

Thanks

**Comment by chris5287** [comment]
Did you specific a token for the npm registry?

Kind regards,
Chris Stylianou

**Comment by crtdaniele** [comment]
Yes, in the credentials, i put

Type: npm_registry
Token: a new token from azure
Registry: pkgs.dev.azure.com

But not work...

Inviato da iPhone XR

> Il giorno 29 set 2020, alle ore 14:53, Chris Stylianou <notifications@github.com> ha scritto:
> 
> ﻿
> Did you specific a token for the npm registry?
> 
> Kind regards,
> Chris Stylianou
>

**Comment by crtdaniele** [comment]
Any idea?

**Comment by chris5287** [comment]
Afraid not, might be worth raising an issue on the dependabot repo.

**Comment by calebmshafer** [comment]
@crtdaniele I ran into the same issue and solved it by using the following configuration,

```
{
    "type" => "npm_registry",
    "token" => ENV['token'], // The token is the base 64 encoded value.  See below
    "registry" => "", //  Including "https://" 
}
```

For the token, you will need to base64 encode the PAT you get from Azure. Here's the script that they provide to do that,

```sh
node -e "require('readline') .createInterface({input:process.stdin,output:process.stdout,historySize:0}) .question('PAT> ',p => { b64=Buffer.from(p.trim()).toString('base64');console.log(b64);process.exit(); })"
```

**Comment by mburumaxwell** [comment]
Try this

https://github.com/tinglesoftware/dependabot-azure-devops/blob/bcc530a03bb3754e8a121236237295623bb787a7/src/script/update-script.rb#L120-L124
